export enum IconEnum {
	add = 'add',
	air = 'air',
	arrowDown = 'arrow-down',
	arrowUp = 'arrow-up',
	close = 'close',
	dark = 'dark',
	explore = 'explore',
	light = 'light',
	location = 'location',
	myLocation = 'myLocation',
	scale = 'scale',
	search = 'search',
	settings = 'settings',
	star = 'star',
	umbrella = 'umbrella',
	visibility = 'visibility',
	water = 'water',
}
